### ISSUE TITLE
[Question] Why do you use YARN instead of NPM?

### ISSUE THREAD

**Issue by johannesschobel** [ahrnee/nestjs-bff#3]
Hey @ahrnee ,

i just stumbled upon this repository and i like it very much. However, i noticed a commit where you switched from `npm` to `yarn`. I was just wondering why!?

all the best

**Comment by ahrnee** [comment]
Hey @johannesschobel,

Thanks.  I have flip-flopped a couple of times.  I have found Yarn to be more stable and reliable.  I was running into weird errors with NPM when I was using more edge-case features (like local file references).  These just want away with Yarn.  

I previously went back from NPM to Yarn when NPM added the security Audit feature... but Yarn just added that also, so that was no longer a game changer.  

Lastly, it is really challenging with Mono-repo TypeScript apps to work out the best blend of Lerna, TypeScript Project References, and Yarn Workspaces to tie it all together.  I have been through a lot of trial-and-error with this, and ultimately ended up with Lerna and TypeScript Project References (not Yarn Workspaces).  However, it is nice to have Yarn Workspaces as an option, if any scenarios come up where it would be useful.

I hope that helps.
